//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlnv
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMCONG
    {
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public System.DateTime NgayThang { get; set; }
        public Nullable<System.TimeSpan> CheckIn { get; set; }
        public Nullable<System.TimeSpan> CheckOut { get; set; }
        public string TG { get; set; }
        public string Thang { get; set; }
    }
}
