//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlnv
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANCONG
    {
        public string MaDA { get; set; }
        public string MaNV { get; set; }
        public string TenNV { get; set; }
    
        public virtual DUAN DUAN { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
