//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlnv
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGBAN
    {
        public string MaPB { get; set; }
        public string TenPB { get; set; }
        public string TruongPhong { get; set; }
        public string TenTrPhong { get; set; }
    
        public virtual STAFF STAFF { get; set; }
    }
}
