//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlnv
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhLuong
    {
        public string ThangNam { get; set; }
        public string MaNV { get; set; }
        public string SoNgayDiLam { get; set; }
        public string SoNgayNghi { get; set; }
        public string SoNgayTre { get; set; }
        public string TienPhat { get; set; }
        public string DuAnThamGia { get; set; }
        public string TienDuAn { get; set; }
        public string LuongCoBan { get; set; }
        public string Luong { get; set; }
    }
}
